CREATE TABLE CARS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(150) NOT NULL,
  CAR_KEY VARCHAR(50) NOT NULL,
  ACTIVE bit NOT NULL DEFAULT 0
);

CREATE TABLE CAR_POSITIONS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  CAR_ID INT NOT NULL,
  LON DECIMAL (18,14),
  LAT DECIMAL (18,14),
  SPEED DECIMAL (10,2),
  DATE_CREATE TIMESTAMP NOT NULL,
  FOREIGN KEY (CAR_ID) REFERENCES CARS(ID)
);